# Generated by Django 3.0.6 on 2020-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Indices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Currrent_value', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
                ('Per_change', models.FloatField(default=0)),
                ('Open', models.FloatField(default=0)),
                ('High', models.FloatField(default=0)),
                ('Low', models.FloatField(default=0)),
                ('pre_close', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MAS_BSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=200)),
                ('Group', models.CharField(max_length=2)),
                ('High', models.FloatField(default=0)),
                ('Low', models.FloatField(default=0)),
                ('Last_Price', models.FloatField(default=0)),
                ('Per_change', models.FloatField(default=0)),
                ('Values_in_RS', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MAS_NSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=200)),
                ('High', models.FloatField(default=0)),
                ('Low', models.FloatField(default=0)),
                ('Last_Price', models.FloatField(default=0)),
                ('Per_change', models.FloatField(default=0)),
                ('Values_in_RS', models.FloatField(default=0)),
            ],
        ),
    ]
