# Generated by Django 3.0.6 on 2020-05-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FD_CASH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_date', models.DateField()),
                ('F_gross_purchase', models.FloatField(default=0)),
                ('F_gross_sales', models.FloatField(default=0)),
                ('F_net_purchase_orsale', models.FloatField(default=0)),
                ('D_gross_purchase', models.FloatField(default=0)),
                ('D_gross_sales', models.FloatField(default=0)),
                ('D_net_purchase_orsale', models.FloatField(default=0)),
            ],
        ),
    ]
