# Generated by Django 3.0.6 on 2020-05-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_fd_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='FD_FII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_date', models.DateField()),
                ('E_gross_purchase', models.FloatField(default=0)),
                ('E_gross_sales', models.FloatField(default=0)),
                ('E_net_purchase_orsale', models.FloatField(default=0)),
                ('DE_gross_purchase', models.FloatField(default=0)),
                ('DE_gross_sales', models.FloatField(default=0)),
                ('DE_net_purchase_orsale', models.FloatField(default=0)),
            ],
        ),
    ]
